# Generated by Django 3.1.5 on 2021-01-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210128_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='is_finished',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_finished',
            field=models.BooleanField(),
        ),
    ]
